### ISSUE TITLE
the client always relink the server automaticlly

### ISSUE THREAD

**Issue by Darley-Wey** [ThallesP/idea-remote-oracle-deploy#1]

**Comment by ThallesP** [comment]
sorry, could you explain what's "relink"?

**Comment by Darley-Wey** [comment]
the connection was broken and the client join the server once and again

**Comment by ThallesP** [comment]
So, what I understand is that when the connection is lost or whatever it reconnects but twice?

**Comment by ThallesP** [comment]
Closing this as no more information was provided.
