### ISSUE TITLE
It does not work as of JetBrains Gateway 2022.1 EAP Build #GW-221.5080.16

### ISSUE THREAD

**Issue by sRaH** [ThallesP/idea-remote-oracle-deploy#2]
They added binaries in a form of remote-dev-worker written in GO and does not contain aarch64 for linux.

- remote-dev-worker-darwin-amd64
- remote-dev-worker-linux-amd64
- remote-dev-worker-darwin-arm64 
- remote-dev-worker-windows-amd64.exe

The client calls for these binaries for backend check/start/connect any command which previously just an ssh command.

So we need to wait sadly.

**Comment by ThallesP** [comment]
Yep, at least it is in EAP still, let's wait for Jetbrains.

**Comment by ThallesP** [comment]
closed as now it supports the newer versions!
