### ISSUE TITLE
What link should be used?

### ISSUE THREAD

**Issue by RomanticD** [ThallesP/idea-remote-oracle-deploy#4]
I saw 3 types of links in the output, Join link, Http link and Gateway link. But none of them works in Jetbrains Gateway for some reason

**Comment by RomanticD** [comment]
I also tried adding ssh-link-option option

**Comment by ThallesP** [comment]
@RomanticD Hey, you should add your remote server to your IDE, for example in Jetbrains Gateway:
![image](https://user-images.githubusercontent.com/76017384/203362100-efd8475f-3c27-413a-b1e5-4363cbb4c5d8.png)


I never tried to add through the link, which doesn't even appear in the YAML file output, I'll give it a try later to see if there's something wrong with it.

**Comment by RomanticD** [comment]
Thanks!
